DROP TABLE IF EXISTS `CUSTOMER_PROFILE`;

CREATE TABLE CUSTOMER_PROFILE
(
    PROFILE_NUMBER BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(20) NOT NULL,
	FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
	ADDRESS VARCHAR(100) NOT NULL,
	POST_CODE VARCHAR(50) NOT NULL,
    MOBILE BIGINT(20),
    EMAIL_ID VARCHAR(100),
	DATE_OF_BIRTH DATE NOT NULL,
	CUSTOMER_TYPE VARCHAR(100) NOT NULL,
	LOAN_TYPE VARCHAR(100) NOT NULL,
	LOAN_AMOUNT BIGINT(100) NOT NULL,
	DURATION_IN_MONTH BIGINT(100) NOT NULL,
	CREATED_BY VARCHAR(100) NOT NULL,
	CREATED_TIME TIMESTAMP NOT NULL,
	EARNING_PER_MONTH DECIMAL NOT NULL,
	EXISTING_EMI_PER_MONTH  DECIMAL NOT NULL,
	EXISTING_RENT  DECIMAL NOT NULL,
	EXISTING_OTHER_EXPENSES DECIMAL NOT NULL,
	ACTIVE VARCHAR(2) NOT NULL  DEFAULT 'Y'  
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX CUST_PROFILE_ID_INDX ON CUSTOMER_PROFILE (PROFILE_NUMBER);

ALTER TABLE CUSTOMER_PROFILE AUTO_INCREMENT=1111; 